version: "3.8"

services:
  app:
    image: medi-sync-backend
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - "8000:8000"
    environment:
      CLOUDINARY_CLOUD_NAME: "dm4vwtxjs"
      CLOUDINARY_API_KEY: "127371483375234"
      CLOUDINARY_API_SECRET: "SwsquzkFInW4tpbnBwi5AlscLEY"
      PORT: 8000
      JWT_ALGORITHM: "HS256"
      JWT_SECRET: "medi-sync-secret"
      FRONTEND_URL: "http://localhost:3000"
      APPWRITE_PROJECT_ID: "67dea36c0038bc1f4adb"
      APPWRITE_ENDPOINT: "https://cloud.appwrite.io/v1"
      APPWRITE_QR_CODES_BUCKET_ID: "67dea41b002a0fbc1ffc"
      APPWRITE_RECORD_PDFS_BUCKET_ID: "67dea4370009b54eacdd"
      DATABASE_URL: "postgresql://neondb_owner:npg_P3fTU2NFpjsv@ep-royal-tree-a5rjcq7k-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require"
    volumes:
      - .:/app
